// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInfoAPI.Data;

#nullable disable

namespace StudentInfoAPI.Migrations
{
    [DbContext(typeof(StudentInfoDbContext))]
    partial class StudentInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("StudentInfoAPI.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2022, 10, 25, 1, 16, 23, 243, DateTimeKind.Utc).AddTicks(1972),
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2022, 10, 25, 1, 16, 23, 243, DateTimeKind.Utc).AddTicks(1977),
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("StudentInfoAPI.Entities.CourseStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Student_Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("StudentInfoAPI.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatricNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2022, 10, 25, 1, 16, 23, 243, DateTimeKind.Utc).AddTicks(2163),
                            MatricNumber = "2017/345",
                            Name = "Zadok Joshua"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2022, 10, 25, 1, 16, 23, 243, DateTimeKind.Utc).AddTicks(2166),
                            MatricNumber = "2017/343",
                            Name = "Trinity Ikpe"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2022, 10, 25, 1, 16, 23, 243, DateTimeKind.Utc).AddTicks(2168),
                            MatricNumber = "2017/343",
                            Name = "James Sam"
                        });
                });

            modelBuilder.Entity("StudentInfoAPI.Entities.CourseStudent", b =>
                {
                    b.HasOne("StudentInfoAPI.Entities.Course", "Course")
                        .WithMany("CourseStudent")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentInfoAPI.Entities.Student", "Student")
                        .WithMany("CourseStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentInfoAPI.Entities.Course", b =>
                {
                    b.Navigation("CourseStudent");
                });

            modelBuilder.Entity("StudentInfoAPI.Entities.Student", b =>
                {
                    b.Navigation("CourseStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
